version: '2'
services:
  flipdot-mqtt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flipdot-mqtt
    restart: unless-stopped
    volumes:
      - ./config.ini:/app/config.ini
